### PR TITLE
Bump to 5.9

### PR DESCRIPTION
**Pull request by liberodark**
screenshot-2021-01-19_20h0424
update fmsx 4.9 (2017) to 5.9 (2020)

Source : http://fms.komkon.org/fMSX/fMSX59.zip
Changelog : https://fms.komkon.org/fMSX/fMSX.html#LABA

@twinaphex bump is now finish

### CODE REVIEW

**Comment by Darknior** [comment]
Great work, so excellent :) Thanks a lot @liberodark

**Comment by Darknior** [comment]
Works fine for me.

**Comment by Syko7956** [comment]
This is amazing! Thank you for doing this

**Comment by twinaphex** [comment]
Some build conflicts here.

**Comment by twinaphex** [comment]
Hi, I will get this merged tomorrow. Thanks for your patience.

**Comment by liberodark** [comment]
@twinaphex Now you can merge without issue.

**Comment by twinaphex** [comment]
Unfortunately this breaks many of our builds. I'm going to roll this back for now since we cannot have it no longer building for several targets.

**Comment by liberodark** [comment]
I tried to fix some of your builds but I couldn't do everything as 5.9 changes a lot of things.
The updates must be followed more often otherwise your work is broken a lot :(

**Comment by twinaphex** [comment]
Unfortunately I will have to revert all this. More care should have been taken to ensure it builds for all our platforms.

I will link to you here everything that was broken by this PR for future reference -
https://git.libretro.com/libretro/fmsx-libretro/-/pipelines/28404

I think we should just make this core a hard fork, it does not make sense to make this a shallow fork when we have to make all these changes/hard edits anyway. All we risk doing is breaking things on our end for no real benefit or gain.

**Comment by twinaphex** [comment]
Will have to force push this.

**Comment by liberodark** [comment]
Sorry but dont have access to your https://git.libretro.com/

**Comment by Darknior** [comment]
Really wish this update will finally be merged, to have an other good MSX emulator to use than only BlueMSX.

**Comment by twinaphex** [comment]
thats because i had to force push to undo the changes since the merge made such a big mess, and then I had to reclone the repo on gitlab.

honestly whenever I have time I will look into it myself

**Pull request merged**
