### PR TITLE
Finally support .cas tape, with autostart

### LINKED ISSUE #23: "Device i/o error" with *.cas files
Verbose log says tape filename is correct, need to check/debug that tape stream actually contains data?

Error seems to signify that no tape is attached?  (according to an experienced MSX user—not me)

### PR DESCRIPTION
**Pull request by cayce-msx**
Fixes #23.

More detailed:
- autodetect .cas format and start it
- link F6 to 'rewind tape' - equal to fMSX keymap
- remove 3 obsolete source files (ConDebug.c, Debug.c, State.h)
- remove 2 unused method headers (InitMachine & TrashMachine)
- resurrect Patch.c; required for Cassette and fmsx_simbdos
- remove Guess Mapper Type B; fmsx-libretro supports only 1 ROM (thus A)
- also support .FDI disk format
- fix inline redefinition warning
- refactor VFS forward declarations

Let me know if this causes build problems for platforms I could not test the build on.

### CODE REVIEW

**Comment by twinaphex** [comment]
I think this is too risky. There are still numerous straight stdio file I/O functions that a straight include of <file_stream_transforms.h> would try to override, with potentially bad consequences.

Far better instead to update libretro-common and use @jdgleaver's new header -

https://github.com/libretro/vitaquake2/blob/libretro/libretro/libretro_file.h

I'd rather you use that instead. Just including <streams/file_stream_transforms.h> like this can potentially blow up.

**Comment by cayce-msx** [comment]
@twinaphex How does that work, updating lr-common? Is that a case of simply copying the whole contents of https://github.com/libretro/libretro-common into fmsx-libretro/libretro-common? Are there any risks involved in _that_? (Apologies, I know a bit of fMSX & the MSX platform, but next to nothing of the internals of RetroArch & libretro.. So yes, I don't _really_ know what I'm doing when including <file_stream_transforms.h>. It compiled & ran fine, but if you're unsure then I am too ;) )

Is it enough to just use https://github.com/libretro/vitaquake2/blob/libretro/libretro/libretro_file.h instead, or must that be used in conjunction with an updated libretro-common?

BTW you state "There are still numerous straight stdio file I/O functions" - are you referring then purely to the fmsx-libretro code itself? Or to code in the 'periphery' of it? The core now only contains 'straight stdio' only for **serial (COM) / 8251** and **printer**, both of which I'd like to drop asap, as both are not applicable to gaming per se.

**Comment by cayce-msx** [comment]
@twinaphex oh I forgot to remark that I did add the following to Makefile.common:
` -DSKIP_STDIO_REDEFINES`
.. because indeed I was a bit queasy about all the `#undef fopen`'s etc. Does that lower your concerns?

If not, just say the word and I'll add the forward references back. I just thought it made the code a bit more tight & nice.

**Comment by jdgleaver** [comment]
@cayce-msx If you set `SKIP_STDIO_REDEFINES` then `file_stream_transforms.h` is benign and no further action should be required

**Comment by twinaphex** [comment]
@jdgleaver How do you think we should proceed here?

**Comment by jdgleaver** [comment]
@twinaphex Since `SKIP_STDIO_REDEFINES` is set in `Makefile.common`, all the dangerous aspects of `file_stream_transforms.h` are avoided. So this PR can be safely merged.

**Pull request merged**
