### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by gingerbeardman**

### CODE REVIEW

**Comment by orbea** [comment]
This PR doesn't apply to master clearnly?
```
$ patch -p1 -i /tmp/fmsx.patch 
patching file libretro.c
Hunk #1 FAILED at 436 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file libretro.c.rej
patching file libretro.c
Hunk #1 FAILED at 436 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file libretro.c.rej
patching file libretro.c
Hunk #1 FAILED at 472 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file libretro.c.rej
patching file libretro.c
Hunk #1 FAILED at 478 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file libretro.c.rej
patching file libretro.c
Hunk #1 FAILED at 253 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file libretro.c.rej
```

**Comment by orbea** [comment]
libretro.c.rej
```
--- libretro.c
+++ libretro.c
@@ -436,7 +436,7 @@ void retro_reset(void)
 
 size_t retro_serialize_size(void)
 {
-   return 0x100000;
+   return (RAMPages + VRAMPages) * 16 * 1024;
 }
 
 bool retro_serialize(void *data, size_t size)
--- libretro.c
+++ libretro.c
@@ -436,7 +436,7 @@ void retro_reset(void)
 
 size_t retro_serialize_size(void)
 {
-   return (RAMPages + VRAMPages) * 16 * 1024;
+   return 0x100000;
 }
 
 bool retro_serialize(void *data, size_t size)
--- libretro.c
+++ libretro.c
@@ -472,8 +472,8 @@ static void check_variables(void)
    var.value = NULL;
 
    Mode = 0;
-   ModeRAM = 0;
-   ModeVRAM = 0;
+   int ModeRAM = 0;
+   int ModeVRAM = 0;
 
    if (environ_cb(RETRO_ENVIRONMENT_GET_VARIABLE, &var) && var.value)
    {
--- libretro.c
+++ libretro.c
@@ -478,17 +478,23 @@ static void check_variables(void)
    if (environ_cb(RETRO_ENVIRONMENT_GET_VARIABLE, &var) && var.value)
    {
       if (strcmp(var.value, "MSX1") == 0)
+      {
          Mode |= MSX_MSX1;
          ModeRAM = 4;
          ModeVRAM = 2;
+      }
       else if (strcmp(var.value, "MSX2") == 0)
+      {
          Mode |= MSX_MSX2;
          ModeRAM = 8;
          ModeVRAM = 8;
+      }
       else if (strcmp(var.value, "MSX2+") == 0)
+      {
          Mode |= MSX_MSX2P;
          ModeRAM = 16;
          ModeVRAM = 8;
+      }
    }
    else
    {
--- libretro.c
+++ libretro.c
@@ -253,7 +253,7 @@ void retro_get_system_info(struct retro_system_info *info)
    info->library_version = "3.9" GIT_VERSION;
    info->need_fullpath = true;
    info->block_extract = false;
-   info->valid_extensions = "rom|mx1|mx2|dsk|cas";
+   info->valid_extensions = "rom|mx1|mx2";
 }
 
 void retro_get_system_av_info(struct retro_system_av_info *info)
```

**Comment by orbea** [comment]
I presume this is something stupid that firefox changed in the way text is copied/pasted...
If I wget the patch it applies fine...

This is where we are at now.
```
cc -o fmsx_libretro.so -shared -Wl,-version-script=link.T -Wl,-no-undefined ./libretro.o ./EMULib/EMULib.o ./EMULib/Sound.o ./fMSX/MSX.o ./fMSX/V9938.o ./fMSX/I8251.o ./EMULib/SHA1.o ./EMULib/Floppy.o ./EMULib/FDIDisk.o ./Z80/Z80.o ./EMULib/I8255.o ./EMULib/YM2413.o ./EMULib/AY8910.o ./EMULib/SCC.o ./EMULib/WD1793.o ./libretro-common/file/retro_dirent.o 
./libretro.o: In function `check_variables':
libretro.c:(.text+0x517d): undefined reference to `strcp'
collect2: error: ld returned 1 exit status
make: *** [Makefile:263: fmsx_libretro.so] Error 1
```

**Comment by gingerbeardman** [comment]
@orbea this file is oddly CRLF line endings, it was changed (not by me) in this commit https://github.com/libretro/fmsx-libretro/commit/c1680634b2ac0a7278398fece093262528125660#diff-52976fe74a1572089032df837f0630a3

**Comment by gingerbeardman** [comment]
@orbea thanks for your patience, typo is fixed

**Comment by orbea** [comment]
Thanks!

**Pull request merged**
